spring:
  application:
    name: weather-query-service
  datasource:
    url: jdbc:h2:mem:weather_db
    driverClassName: org.h2.Driver
    username: ${DATABASE_USERNAME:sa}
    password: ${DATABASE_PASSWORD:password}
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

open-weather-map-api:
  base-url: https://api.openweathermap.org
  api-key: ${OPEN_WEATHER_API_KEY:d21af51e285cb140f77d3c84a3bace55}

api-key:
  time_period_in_minutes: 60
  request_rate_allowed_for_period: 5